spring:
  application:
    name: monk-commerce
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://monk-commerce-db:5432/monk-commerce
    username: root
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080